# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='work_images/%Y/%m/%d'),
        ),
    ]
