# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20160328_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(null=True, upload_to='work_images/%Y/%m/%d'),
        ),
    ]
