# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20160328_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.FileField(upload_to='work_images/%Y/%m/%d'),
        ),
    ]
